# Generated by Django 5.2.7 on 2025-11-04 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True)),
                ('a_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='trips.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='EUR', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True)),
                ('tipo_reparto', models.CharField(default='igual', max_length=20)),
                ('pagado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='trips.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='trips.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lugar', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ParteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_parte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saldado', models.BooleanField(default=False)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='trips.gasto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gasto', 'usuario')},
            },
        ),
    ]
